[grupo 11] requisito 5
tryber/sd-010-a-project-frontend-online-store pull request #125
Opened 2021-05-15 00:32 UTC by rogerio-lambert

2021-05-15 13:57 UTC, gustavofds commented
Boa!! Deu conflito mas é fácil de resolver. Basta manter as 2 alterações. Só não entendi porque não rodou o avaliador.

2021-05-15 18:00 UTC, michael-petterson-06 approved these changes

2021-05-15 18:57 UTC, gustavofds approved these changes

2021-05-15 19:02 UTC, gustavofds requested changes
Aprovei o PR e resolvi o conflito, e só depois o avaliador rodou. Aí apareceram os erros no lint.

2021-05-17 18:05 UTC, gustavofds approved these changes

2021-05-17 18:19 UTC, merged