[ Group 2 ] requiment05
tryber/sd-010-a-project-frontend-online-store pull request #132
Opened 2021-05-15 17:28 UTC by NilsonRCS

2021-05-15 19:42 UTC, AndersonNascimentoAFSN approved these changes

2021-05-15 20:12 UTC, beatriz-estebanez approved these changes
Muito bom pessoal!

2021-05-15 21:36 UTC, sergiomos requested changes

2021-05-15 21:36 UTC, sergiomos commented on src/pages/Home.js
> +  fetchResponse = async () => {
Talvez o nome dessa função poderia  ser algo mais  intuitivo, como fetchProducts ou  fetchAllProducts, o que acham?

2021-05-15 21:36 UTC, sergiomos commented on src/pages/Home.js
> +  fetchResponse = async () => {
Talvez trocar o  nome dessa função para `fetchProducts` ou `fetchAllProducts`, deixaria mais  intuitive , o  que acham?

2021-05-15 21:36 UTC, sergiomos commented on src/components/CardItem.js
> +        ))}
O que acham de deixar  a responsabilidade de renderiza ar os produtos ao componente pai (Home), e o componente `CardItem` recebendo a props de cada produto? Desse jeito, ao ler o componente pai, conseguimos  saber com facilidade de onde a lista de produtos está surgindo.
```suggestion
    const { title, price, thumbnail, id } = this.props;
    return (
        <div data-testid="product" key={ id }>
          <h2>{ title }</h2>
          <span>{ price }</span>
          <img src={ thumbnail } alt="alt" />
        </div>
       )
```

2021-05-15 21:36 UTC, sergiomos commented on src/pages/Home.js
> +        <CardItem products={ products } />
O pai renderiza  todos os filhos
```suggestion
        { productts.map((product) =>  <CardItem product={ products } />)}
```

2021-05-15 22:48 UTC, AndersonNascimentoAFSN commented on src/pages/Home.js
> +  fetchResponse = async () => {
Concordo. fetchProducts fica mais especifíco.

2021-05-17 13:12 UTC, beatriz-estebanez commented on src/pages/Home.js
> +  fetchResponse = async () => {
Concordo Sérgio! Podemos trocar sim.

2021-05-17 13:17 UTC, beatriz-estebanez commented on src/components/CardItem.js
> +        ))}
Concordo com a alteração Sérgio, ficaria bem melhor estruturado. Podemos trabalhar nisso hoje. :)

2021-05-17 14:12 UTC, juliabaptista commented on src/pages/Home.js
> +  fetchResponse = async () => {
Boa!

2021-05-17 17:59 UTC, juliabaptista approved these changes
show galera !!

2021-05-17 17:59 UTC, AndersonNascimentoAFSN approved these changes

2021-05-17 18:04 UTC, sergiomos approved these changes

2021-05-17 19:34 UTC, closed without merging