[Grupo 4] feat: requisito 4
tryber/sd-010-a-project-frontend-online-store pull request #96
Opened 2021-05-14 21:40 UTC by ThalitaC

2021-05-14 21:46 UTC, teudm commented on src/App.css
>  }
Tomei susto de tanta coisa vermelha

2021-05-14 21:46 UTC, teudm approved these changes

2021-05-14 21:58 UTC, teudm approved these changes
Aqui também rodou após comentar

2021-05-16 01:30 UTC, o-flores requested changes

2021-05-16 01:30 UTC, o-flores commented on src/components/Categories.jsx
> +    this.setState({ categories: [] }, () => {
Thalita,me tira uma duvida.... é realmente necessário dar de novo o estado de categories de um array vazio? pq isso vc ja faz la no constructor. Eu pensei que seria possivel realizar a busca pra API apenas com as linhas 19 e 20 :)

2021-05-16 14:24 UTC, ThalitaC commented on src/components/Categories.jsx
> +    this.setState({ categories: [] }, () => {
Opa, vc tá certo, dá sim, corrigi aqui ;)

2021-05-17 14:50 UTC, o-flores approved these changes

2021-05-17 15:01 UTC, merged